apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: tech-challenge
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: tech-challenge-fiap
data:
  NODE_ENV: production
  PORT: "3000"
  JWT_ACCESS_EXPIRES_IN: 15m
  JWT_REFRESH_EXPIRES_IN: 7d
